local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("boilerplate", {
    t({
      "# vim: filetype=make",
      ".ONESHELL:",
      "",
      "OS := $(shell uname -s | tr '[:upper:]' '[:lower:]')",
      "ENV_FILE := \"env_file\"",
      "COMPOSE := docker compose",
      "",
      "export OS := $(OS)",
      "",
      "#> Setup.",
      "",
      "setup:: ## setup the development environment",
      "setup:: precommit-install",
      ".PHONY: setup",
      "",
      "precommit-install: ## install pre-commit hooks",
      "\tpre-commit install",
      "",
      "#> Docker.",
      "",
      "docker-build-all::  ## build all docker stages",
      "docker-build-all:: docker-build-base",
      "docker-build-all:: docker-build-deps",
      ".PHONY: docker-build-all",
      "",
      "docker-build-%:",
      "\tdocker build -t clickhouse-dbt-$* --target $* .",
      ".PHONY: docker-build-%",
      "",
      "compose-build: ## build the development env within docker comopose",
      "\t$(COMPOSE) build",
      ".PHONY: compose-build",
      "",
      "up: ## bring up the stack",
      "\t$(COMPOSE) up -d",
      "\t$(COMPOSE) attach clickhouse",
      ".PHONY: up",
      "",
      "down: ## pause the stack",
      "\t$(COMPOSE) down",
      ".PHONY: down",
      "",
      "compose-teardown: ## stop the stack, deleting orphans and volumes",
      "\t$(COMPOSE) down -v --remove-orphans",
      ".PHONY: compose-teardown",
      "",
      "#> Lint and Format.",
      "",
      "lint:: ## lint all files",
      ".PHONY: lint",
      "",
      "format:: ## autoformat all files",
      ".PHONY: format",
      "",
      "precommit: ## run all pre-commit hooks manually",
      "\tpre-commit run --all-files",
      ".PHONY: precommit",
      "",
      "",
      "#> Utility.",
      "help: ## show this help",
      "\t@echo \"Specify a command from the list below:\"",
      "\t@echo \"\"",
      "\t@awk 'BEGIN {FS = \":.*?## \"}; \\",
      "\t\t/^#> / { \\",
      "\t\t\tgsub(/^#> /, \"\", $0); \\",
      "\t\t\tprintf \"\\n\\033[1;35m%s\\033[m\\n\", $0; \\",
      "\t\t\tnext \\",
      "\t\t} \\",
      "\t\t/^[0-9a-zA-Z_-]+:.*?## / { \\",
      "\t\t\tprintf \"  \\033[0;36m%-20s\\033[m %s\\n\", $1, $2 \\",
      "\t\t}' $(MAKEFILE_LIST)",
      "\t@echo \"\"",
      ".PHONY: help",
      "",
      "",
    }),
  }),
}
