# sanoid.conf
#
# This file should be in /etc/sanoid/sanoid.config for discovery by the default
# Sanoid systemd timer.

#############################
# templates.
#############################

[template_production]
# critical "working set" data with frequent snapshots and limited large files
#
# 4 frequently (every 15 minutes), 24 hourly, 7 daily, 4 weekly, 1 monthly on source
    frequently = 4
    hourly = 24
    daily = 7
    weekly = 4
    monthly = 1
    yearly = 0
    autosnap = yes
    autoprune = yes

[template_media]
# large, slow-moving data
#
# 7 daily, 4 weekly, 1 monthly, 1 yearly
    frequently = 0
    hourly = 0
    daily = 7
    weekly = 4
    monthly = 1
    yearly = 1
    autosnap = yes
    autoprune = yes

#############################
# system datasets.
#############################

[zroot/ROOT/ubuntu]
use_template = production
recursive = true

# System dataset-specific snapshot exclusions.
#
# Do not create snapshots for tmp and cache directories.
[zroot/ROOT/ubuntu/tmp]
autosnap = no
autoprune = yes

[zroot/ROOT/ubuntu/var/tmp]
autosnap = no
autoprune = yes

[zroot/ROOT/ubuntu/var/cache]
autosnap = no
autoprune = yes

#############################
# user datasets.
#############################

[zroot/home]
use_template = production
recursive = true

# Dataset-specific overrides.
#
# The configurations below override the zroot/home configuration above.
[zroot/home/heatmiser/Videos]
use_template = media

[zroot/home/heatmiser/Movies]
use_template = media

[zroot/home/heatmiser/Pictures]
use_template = media

# User dataset-specific snapshot exclusions.
#
# Do not create snapshots for cache and trash directories.
[zroot/home/heatmiser/.cache]
autosnap = no
autoprune = yes

[zroot/home/heatmiser/.local/share/Trash]
autosnap = no
autoprune = yes

[zroot/home/heatmiser/.local/state]
autosnap = no
autoprune = yes
